# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(default='', max_length=1024)),
                ('prod_id', models.CharField(default='', max_length=1024, primary_key=True, serialize=False)),
                ('last_crawl_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.CharField(default='', max_length=1024)),
                ('text_content', models.CharField(default='', max_length=1024)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('content', models.TextField(default='')),
                ('review_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=1024)),
                ('user_id', models.CharField(default='', max_length=1024, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
