# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_crawl_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationship',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationship',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
