# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_id',
            new_name='asin',
        ),
    ]
