# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170924_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
