# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170924_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_sentence', models.CharField(default='', max_length=1023)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
                ('related_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Review')),
            ],
        ),
    ]
