# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
